# Generated by Django 3.2.2 on 2021-05-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0005_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('C', 'Car'), ('M', 'Motorcycle')], max_length=1)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateField()),
                ('amount_paid', models.FloatField()),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='levels.space')),
            ],
        ),
    ]
