# Generated by Django 3.2.2 on 2021-05-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210517_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
