# Generated by Django 3.2.2 on 2021-05-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fill_priority', models.IntegerField()),
                ('motorcylce_spaces', models.IntegerField()),
                ('car_spaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='levels.level')),
            ],
        ),
    ]
