# Generated by Django 3.2.2 on 2021-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_alter_space_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_coefficient', models.IntegerField()),
                ('b_coefficient', models.IntegerField()),
            ],
        ),
    ]
