# Generated by Django 3.2.2 on 2021-05-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='filled',
        ),
    ]
